### ISSUE TITLE
【メロンブックス】イベントタグの取得エラー

### ISSUE THREAD

**Issue by Winding6636** [marron-akanishi/kotori#37]
書籍追加/メロンブックスにて、追加時エラー
おそらく、イベント未指定で表示されていないことからの取得エラー？

[該当例](https://www.melonbooks.co.jp/detail/detail.php?product_id=511652)

[Error at _book_add_detail.txt](https://cloud.mbius.io/s/WfGqxAY87Qn2DMT)
[Error at _book_add_detail.png](https://cloud.mbius.io/s/GpZNFyrfm2ysbxg)

**Comment by marron-akanishi** [comment]
SiteParserのリファクタリングと共に修正しました。
